version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:80"  # React estará disponible en http://localhost:3000
    restart: unless-stopped

